default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: my-secret-pw
  host: mysql
  # host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: chat_messages_system_development

test:
  <<: *default
  database: chat_messages_system_test

production:
  <<: *default
  database: chat_messages_system_production
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || 'my-secret-pw' %>
  host: mysql
  port: 3306
