# Use the official Redis image from Docker Hub
FROM redis:latest

# Expose the port 6400 to be accessible outside the container
EXPOSE 6400

# Command to run Redis on port 6400
CMD ["redis-server", "--port", "6400"]
